apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pokemon-main
  labels:
    app: pokemon-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-main
  template:
    metadata:
      labels:
        app: pokemon-main
    spec:
      containers:
        - name: pokemon-main
          image: rbaliyan/pokemon-micro:1.0.3-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: DATABASE
              value: db_pokemon
            - name: MYSQL_HOST
              value: mysql-pokemon-main
            - name: REDIS_HOST
              value: redis
            - name: ABILITY_URL
              value: ability-service

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-pokemon-main
  labels:
    app: mysql-pokemon-main
spec:
  selector:
    matchLabels:
      app: mysql-pokemon-main
  template:
    metadata:
      labels:
        app: mysql-pokemon-main
    spec:
      containers:
        - name: mysql-pokemon-main
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: "db_pokemon"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: my-sql-pokemon-main
      volumes:
        - name: my-sql-pokemon-main

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ability
  labels:
    app: ability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ability
  template:
    metadata:
      labels:
        app: ability
    spec:
      containers:
        - name: ability
          image: rbaliyan/abilities:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: POKEMON_MAIN_URL
              value: pokemon-main
            - name: MYSQL_HOST
              value: mysql-ability
            - name: DATABASE
              value: ability
            - name: REDIS_HOST
              value: redis

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-ability
  labels:
    app: mysql-ability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ability
  template:
    metadata:
      labels:
        app: mysql-ability
    spec:
      containers:
        - name: mysql-service
          image: mysql:5.7
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              value: "ability"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: my-sql-ability
      volumes:
        - name: my-sql-ability
