apiVersion: v1
kind: Service
metadata:
  name: pokemon-main
spec:
  selector:
    app: pokemon-main
  ports:
    - port: 8080
      nodePort: 30022
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-pokemon-main
spec:
  selector:
    app: mysql-pokemon-main
  ports:
    - port: 3306
      nodePort: 30023
  type: NodePort

