apiVersion: v1
kind: Service
metadata:
  name: pokemon-main
spec:
  selector:
    app: pokemon-main
  ports:
    - port: 8080
      nodePort: 30022
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-pokemon-main
spec:
  selector:
    app: mysql-pokemon-main
  ports:
    - port: 3306
      nodePort: 30023
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: ability-service
spec:
  selector:
    app: ability-service
  ports:
    - port: 8080
      nodePort: 30024
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-ability
spec:
  selector:
    app: mysql-ability
  ports:
    - port: 3306
      nodePort: 30025
  type: NodePort


